---
- name: Setup control machine
  hosts: control
  
  roles:
    - fwsquatch.setup_control

  post_tasks:
    - name: Create files directory
      file:
        path: /home/vagrant/files
        owner: vagrant
        group: vagrant
        state: directory

    - name: copy files to control
      copy:
        src: ../setup/files/.vimrc
        dest: /home/vagrant/files/.vimrc
        owner: vagrant
        group: vagrant
        mode: 0644

- name: Setup practice nodes
  hosts:
    - node1
    - node2
  roles:
  
    - fwsquatch.setup_node
