---
# tasks file for fwsquatch.setup_node

- name: Set up /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      192.168.88.100 control.rhce.lab control
      192.168.88.101 node1.rhce.lab node1
      192.168.88.102 node2.rhce.lab node2
      192.168.88.103 node3.rhce.lab node3
      192.168.88.104 node4.rhce.lab node4
      192.168.88.105 node5.rhce.lab node5

- name: Copy key to .ssh/authorized_keys
  copy:
    content: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"
    dest: /home/vagrant/.ssh/authorized_keys
    owner: vagrant
    group: vagrant
    mode: 0600

- name: Create the motd file
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
